[cr148][Android] Fix missing androidx_activity_activity_java dep in androidx_fragment_fragment
Upstream androidx roll removed `androidx_activity_activity_java` from
`androidx_fragment_fragment` deps. This broke compilation because
`Fragment.registerForActivityResult` references
`androidx.activity.result.contract.ActivityResultContract` from that lib:

  obj/.../androidx_fragment_fragment_java.ijar.jar:
  error: Cannot attach type annotations to Fragment.registerForActivityResult:
    class file for androidx.activity.result.contract.ActivityResultContract not found

Chromium change:
https://source.chromium.org/chromium/chromium/src/+/ada9ea879eecaba01f2f1ee9c3e463d3ad743ae7

commit ada9ea879eecaba01f2f1ee9c3e463d3ad743ae7
Author: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Date:   Tue Mar 31 01:34:26 2026 -0700

    Roll androidx from gC_MaDqHwyg6cLUuq... to WDVd3JIX6yvavWuXd...

    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/androidx-chromium
    Please CC clank-build@google.com,clank-library-failures@google.com,wnwen@google.com on the revert to ensure that a human
    is aware of the problem.

    To file a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/entry

    To report a problem with the AutoRoller itself, please file a bug:
    https://issues.skia.org/issues/new?component=1389291&template=1850622

    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

    Cq-Include-Trybots: luci.chrome.try:android-internal-binary-size;luci.chrome.try:android-internal-rel;luci.chrome.try:test-emulator
    Tbr: clank-library-failures@google.com
    Change-Id: I4e9302dd90c5b5eaabf19cb7a31f19120354b74f
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7713047
    Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
    Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
    Cr-Commit-Position: refs/heads/main@{#1607712}